### ISSUE TITLE
Issue with pip

### ISSUE THREAD

**Issue by barrachri** [agiliq/django-graphos#18]
Hi, I have this error with pip 1.4.1:

$ pip install django-graphos
Downloading/unpacking django-graphos
Could not find a version that satisfies the requirement django-graphos (from versions: 0.0.1a0, 0.0.2a0)
Cleaning up...
No distributions matching the version for django-graphos

**Comment by munnerz** [comment]
This still isn't fixed FYI - any updates or plans to fix?

**Comment by miscaandrei** [comment]
Hi I'm working with pip version 1.5.6 and python 2.7
The standard pip install commands still doesn't work so I had to install it with the version specification.
My opinion is that until you can fix this bug, you should put in the main wiki/manual the full command (pip install django-graphos==0.0.2a0) just in case someone else tries to install django-graphos won't get frustrated because of the error.

**Comment by akshar-raaj** [comment]
@miscaandrei @munnerz @luukholleman @barrachri Thanks for bringing it to notice! It should be fixed now.
