### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Connection'

### ISSUE THREAD

**Issue by wynnfynn** [agiliq/django-graphos#29]
pymongo.Connection is not support ,  please fix it. thx
 django-graphos-master/demo_project/demo/utils.py  
1 import pymongo
  2 from pymongo import MongoClient
  3 from .models import Account
  4 
  5 
  6 DB_HOST = ["localhost"]
  7 DB_PORT = 27017
  8 
  9 
 10 def get_db(db_name):
 11     DB_HOST = ["localhost"]
 12     DB_PORT = 27017
 13     #db = pymongo.Connection(DB_HOST, DB_PORT)[db_name]
 14     db = MongoClient(DB_HOST, DB_PORT)[db_name]
 15     return db
 16 
 17 
 18 def get_mongo_cursor(db_name, collection_name, max_docs=100):
 19     #db = pymongo.Connection(host=DB_HOST,
 20     db = MongoClient(host=DB_HOST,
 21                             port=DB_PORT)[db_name]
 22     collection = db[collection_name]
 23     cursor = collection.find()
 24     if cursor.count >= max_docs:
 25         cursor = cursor[0:max_docs]
 26     return cursor

**Comment by akshar-raaj** [comment]
@wynnfynn Not sure what your issue is.

If you look at demo_project/requirements.txt, https://github.com/agiliq/django-graphos/blob/master/demo_project/requirements.txt#L7, and install pymongo, then things should work as expected.

I started a `python manage.py shell` and was able to do `from pymongo import Connection`. Can you be more explicit about the error you are facing.
